source/accounts/urls.py
from django.urls import path

from accounts.views import UserListView, UserLogoutView, UserLoginView, UserCreateView, UserChangeView, UserDeleteView

urlpatterns = [
    path('users/register/', UserCreateView.as_view(), name='register_user'),
    path('users/<int:pk>/edit/', UserChangeView.as_view(), name='change_user'),
    path('users/login/', UserLoginView.as_view(), name='login'),
    path('users/logout/', UserLogoutView.as_view(), name='logout'),
    path('users/', UserListView.as_view(), name='list_users'),
    path('users/<int:pk>/delete/', UserDeleteView.as_view(), name='delete_user'),
]

app_name = 'accounts'

source/api_v1/urls.py
from django.urls import path

from api_v1.views import CategoryAddView, CategoryDeleteView, CategoryListView, ArticleListView

urlpatterns = [
    path('categories/add', CategoryAddView.as_view(), name='create_category'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='delete_category'),
    path('categories/', CategoryListView.as_view(), name='list_categories'),
    path('articles/', ArticleListView.as_view(), name='list_articles'),
]

app_name ='api_v1'

source/main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views.article_views import ArticleListView, ArticleEditView, ArticleDeleteView, ArticleCreateView
from webapp.views.category_views import CategoryListView, CategoryEditView

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='list_categories'),
    path('categories/<int:pk>/edit/', CategoryEditView.as_view(), name='edit_category'),
    path('', ArticleListView.as_view(), name='list_articles'),
    path('articles/add/', ArticleCreateView.as_view(), name='add_article'),
    path('articles/<int:pk>/edit/', ArticleEditView.as_view(), name='edit_article'),
    path('articles/<int:pk>/delete/', ArticleDeleteView.as_view(), name='delete_article'),
]

app_name = 'webapp'

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=30, verbose_name='Название категории')
    parent_id = models.ForeignKey('self', null=True, blank=True, verbose_name='Название основной категории',
                                  on_delete=models.PROTECT)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Categories'

class Article(models.Model):
    category_id = models.ForeignKey('webapp.Category', verbose_name='Категория', on_delete=models.PROTECT)
    user_id = models.ForeignKey(User, verbose_name='Автор статьи', null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=50, verbose_name='Название статьи')
    description = models.TextField(max_length=3000, verbose_name='Текст статьи')
    image = models.ImageField(upload_to='articles_images/', verbose_name='Аватар статьи')

    def __str__(self):
        if self.user_id:
            return "Статья {} от {}".format(self.title, self.user_id.username)
        else:
            return "Статья {}".format(self.title)

source/webapp/forms.py
from django import forms

from webapp.models import Category, Article


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title', 'parent_id']


class ArticleFormForAuthor(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'category_id', 'description', 'image']


class ArticleFormForStaff(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'category_id', 'user_id', 'description', 'image']

source/webapp/views/article_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, UpdateView, CreateView

from webapp.forms import ArticleFormForAuthor, ArticleFormForStaff
from webapp.models import Article


class ArticleListView(PermissionRequiredMixin, ListView):
    model = Article
    template_name = 'article/list.html'
    context_object_name = 'articles'
    paginate_by = 10
    paginate_orphans = 2
    permission_required = ['webapp.view_article']
    permission_denied_message = ['Доступ ограничен']


class ArticleEditView(UserPassesTestMixin, UpdateView):
    model=Article
    form_class = ArticleFormForAuthor
    template_name = 'article/edit.html'

    def form_valid(self, form):
        self.object = form.save()
        self.object.user_id = self.request.user
        return super(ArticleEditView, self).form_valid(form)

    def get_form(self, form_class=None):
        if self.request.user.has_perm('auth.view_user'):
            self.form_class = ArticleFormForStaff
        return super(ArticleEditView, self).get_form(form_class)

    def get_success_url(self):
        return reverse('webapp:list_articles')

    def get_article(self):
        article_pk = self.kwargs['pk']
        return get_object_or_404(Article, pk=article_pk)

    def test_func(self):
        article = self.get_article()
        return self.request.user.has_perm('webapp.change_article') or self.request.user.id == article.user_id.id


class ArticleDeleteView(PermissionRequiredMixin, View):
    permission_required = ['webapp.delete_article']
    permission_denied_message = ['Доступ ограничен']

    def get(self, request, *args, **kwargs):
        article = self.get_article()
        article.delete()
        return redirect('webapp:list_articles')

    def get_article(self):
        article_pk = self.kwargs['pk']
        return get_object_or_404(Article, pk=article_pk)


class ArticleCreateView(PermissionRequiredMixin, CreateView):
    model = Article
    form_class = ArticleFormForAuthor
    template_name = 'article/create.html'
    permission_required = ['webapp.add_article']
    permission_denied_message = ['Доступ ограничен']

    def get_success_url(self):
        return reverse('webapp:list_articles')

    def get_form(self, form_class=None):
        if self.request.user.has_perm('auth.view_user'):
            self.form_class = ArticleFormForStaff
        return super(ArticleCreateView, self).get_form(form_class)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            self.object = form.save()
            if not request.user.has_perm('webapp.view_user'):
                self.object.user_id = request.user
                self.object.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

source/webapp/views/category_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import ListView, UpdateView

from webapp.forms import CategoryForm
from webapp.models import Category


class CategoryListView(PermissionRequiredMixin, ListView):
    model = Category
    template_name = 'category/list.html'
    context_object_name = 'categories'
    paginate_by = 10
    paginate_orphans = 2
    permission_required = ['webapp.view_category']
    permission_denied_message = ['Доступ ограничен']
    ordering = ['title']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['form'] = CategoryForm
        return context


class CategoryEditView(PermissionRequiredMixin, UpdateView):
    model = Category
    fields = ['title', 'parent_id']
    template_name = 'category/category_edit.html'
    permission_required = ['webapp.change_category']
    permission_denied_message = ['Доступ ограничен']

    def get_success_url(self):
        return reverse('webapp:list_categories')

source/webapp/templates/category/category_add.html
{% extends 'base.html' %}
{% block title %}
    Добавить категорию
{% endblock %}

{% block content %}
    <h1>Добавить категорию</h1>
    <form action="{% url 'webapp:add_category' %}" method="POST">
        {% include 'partial/form.html' with button_text='Добавить' %}
    </form>
{% endblock %}

source/webapp/templates/category/category_delete.html
{% extends 'base.html' %}
{% block title %}
    Удалить категорию
{% endblock %}
{% block content %}
    <h1>Удалить категорию "{{ category.title }}"</h1>
    <form action="{% url 'webapp:delete_category' category.pk %}" method="POST">
        {% csrf_token %}
        <h2>Вы действительно хотите удалить категорию {{ category.title }}?</h2>
        <input type="submit" class="btn btn-danger" value="Удалить">
        <a href="{% url 'webapp:list_categories' %}" class="btn btn-success">Отмена</a>
    </form>
{% endblock %}

source/webapp/templates/category/category_edit.html
{% extends 'base.html' %}
{% block title %}
   Редактировать категорию
{% endblock %}
{% block content %}
    <h1>Редактировать категорию</h1>
    <form action="{% url 'webapp:edit_category' category.pk %}" method="POST">
        {% include 'partial/form.html' with button_text='Редактировать' button_id='editCategory'%}
    </form>
{% endblock %}

source/webapp/templates/category/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Категории
{% endblock %}
{% block menu_links %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'webapp:list_articles' %}">К списку статей</a>
    </li>
    {% if perms.auth.view_user %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="usersDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Пользователи
            </a>
            <div class="dropdown-menu" aria-labelledby="usersDropdown">
                <a class="dropdown-item" href="{% url 'accounts:list_users' %}">К списку пользователей</a>
                <a class="dropdown-item" href="{% url 'accounts:register_user' %}">Добавить пользователя</a>
            </div>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
        {% include  'partial/pagination.html' %}
    <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <span><b>Список категорий статей</b></span>
            <span><b>Действия</b></span>
        </li>
        {% for category in categories %}
            <li class="list-group-item d-flex justify-content-between align-items-center" id="category_item_{{ category.pk }}">
                <div>
                    <p>{{ category.title }} {% if category.parent_id %}(основная категория <strong>{{ category.parent_id.title }}</strong>){% endif %}</p>
                </div>
                {% if perms.webapp.change_category %}
                    <div class="btn-group">
                        <a href="{% url 'webapp:edit_category' category.pk %}" id="category_edit_{{ category.pk }}" class="btn btn-success">Редактировать</a>
                        <button id="category_delete_{{ category.pk }}" class="btn btn-warning button-delete" data-id="{{ category.pk }}">Удалить</button>
                    </div>
                {% endif %}
            </li>
        {% endfor %}
        {% if perms.webapp.add_category %}
            <li class="list-group-item" id="collapseFormItem">
                <div class="collapse" id="collapseCategory">
                    <form class="form-inline pt-3 pb-3" id="сategoryForm">
                        {% include 'partial/form.html' with button_id='addCategoryFormSubmit' button_text='Добавить категорию'%}
                    </form>
                </div>
                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseCategory" aria-expanded="false" aria-controls="collapseCategory">
                    Добавить категорию
                </button>
            </li>
        {% endif %}
    </ul>
        {% include  'partial/pagination.html' %}
{% endblock %}

{% block script %}
    <script src="{% static 'js/category.js' %}"></script>
{% endblock %}