source/accounts/urls.py
from django.urls import path

from accounts.views import UserListView, UserLogoutView, UserLoginView, UserCreateView, UserChangeView, UserDeleteView

urlpatterns = [
    path('users/register/', UserCreateView.as_view(), name='register_user'),
    path('users/<int:pk>/edit/', UserChangeView.as_view(), name='change_user'),
    path('users/login/', UserLoginView.as_view(), name='login'),
    path('users/logout/', UserLogoutView.as_view(), name='logout'),
    path('users/', UserListView.as_view(), name='list_users'),
    path('users/<int:pk>/delete/', UserDeleteView.as_view(), name='delete_user'),
]

app_name = 'accounts'

source/main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views.article_views import ArticleListView, ArticleEditView, ArticleDeleteView, ArticleCreateView
from webapp.views.category_views import CategoryListView, CategoryEditView

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='list_categories'),
    path('categories/<int:pk>/edit/', CategoryEditView.as_view(), name='edit_category'),
    path('', ArticleListView.as_view(), name='list_articles'),
    path('articles/add/', ArticleCreateView.as_view(), name='add_article'),
    path('articles/<int:pk>/edit/', ArticleEditView.as_view(), name='edit_article'),
    path('articles/<int:pk>/delete/', ArticleDeleteView.as_view(), name='delete_article'),
]

app_name = 'webapp'

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=30, verbose_name='Название категории')
    parent_id = models.ForeignKey('self', null=True, blank=True, verbose_name='Название основной категории',
                                  on_delete=models.PROTECT)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Categories'

class Article(models.Model):
    category_id = models.ForeignKey('webapp.Category', verbose_name='Категория', on_delete=models.PROTECT)
    user_id = models.ForeignKey(User, verbose_name='Автор статьи', null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=50, verbose_name='Название статьи')
    description = models.TextField(max_length=3000, verbose_name='Текст статьи')
    image = models.ImageField(upload_to='articles_images/', verbose_name='Аватар статьи')

    def __str__(self):
        if self.user_id:
            return "Статья {} от {}".format(self.title, self.user_id.username)
        else:
            return "Статья {}".format(self.title)

source/webapp/forms.py
from django import forms

from webapp.models import Category, Article


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title', 'parent_id']


class ArticleFormForAuthor(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'category_id', 'description', 'image']


class ArticleFormForStaff(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'category_id', 'user_id', 'description', 'image']

source/webapp/views/article_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, UpdateView, CreateView

from webapp.forms import ArticleFormForAuthor, ArticleFormForStaff
from webapp.models import Article


class ArticleListView(PermissionRequiredMixin, ListView):
    model = Article
    template_name = 'article/list.html'
    context_object_name = 'articles'
    paginate_by = 10
    paginate_orphans = 2
    permission_required = ['webapp.view_article']
    permission_denied_message = ['Доступ ограничен']


class ArticleEditView(UserPassesTestMixin, UpdateView):
    model=Article
    form_class = ArticleFormForAuthor
    template_name = 'article/edit.html'

    def form_valid(self, form):
        self.object = form.save()
        self.object.user_id = self.request.user
        return super(ArticleEditView, self).form_valid(form)

    def get_form(self, form_class=None):
        if self.request.user.has_perm('auth.view_user'):
            self.form_class = ArticleFormForStaff
        return super(ArticleEditView, self).get_form(form_class)

    def get_success_url(self):
        return reverse('webapp:list_articles')

    def get_article(self):
        article_pk = self.kwargs['pk']
        return get_object_or_404(Article, pk=article_pk)

    def test_func(self):
        article = self.get_article()
        return self.request.user.has_perm('webapp.change_article') or self.request.user.id == article.user_id.id


class ArticleDeleteView(PermissionRequiredMixin, View):
    permission_required = ['webapp.delete_article']
    permission_denied_message = ['Доступ ограничен']

    def get(self, request, *args, **kwargs):
        article = self.get_article()
        article.delete()
        return redirect('webapp:list_articles')

    def get_article(self):
        article_pk = self.kwargs['pk']
        return get_object_or_404(Article, pk=article_pk)


class ArticleCreateView(PermissionRequiredMixin, CreateView):
    model = Article
    form_class = ArticleFormForAuthor
    template_name = 'article/create.html'
    permission_required = ['webapp.add_article']
    permission_denied_message = ['Доступ ограничен']

    def get_success_url(self):
        return reverse('webapp:list_articles')

    def get_form(self, form_class=None):
        if self.request.user.has_perm('auth.view_user'):
            self.form_class = ArticleFormForStaff
        return super(ArticleCreateView, self).get_form(form_class)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            self.object = form.save()
            if not request.user.has_perm('webapp.view_user'):
                self.object.user_id = request.user
                self.object.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

source/webapp/views/category_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import ListView, UpdateView

from webapp.forms import CategoryForm
from webapp.models import Category


class CategoryListView(PermissionRequiredMixin, ListView):
    model = Category
    template_name = 'category/list.html'
    context_object_name = 'categories'
    paginate_by = 10
    paginate_orphans = 2
    permission_required = ['webapp.view_category']
    permission_denied_message = ['Доступ ограничен']
    ordering = ['title']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['form'] = CategoryForm
        return context


class CategoryEditView(PermissionRequiredMixin, UpdateView):
    model = Category
    fields = ['title', 'parent_id']
    template_name = 'category/category_edit.html'
    permission_required = ['webapp.change_category']
    permission_denied_message = ['Доступ ограничен']

    def get_success_url(self):
        return reverse('webapp:list_categories')

source/webapp/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "/css/style.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {% block style_links %}{% endblock %}
</head>
<body>
<header>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'webapp:list_articles' %}">Очень крутой бренд</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav ml-auto">
                    {% if request.user.is_authenticated %}
                        <span class="navbar-text">Привет, </span>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ request.user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a href="{% url 'accounts:change_user' request.user.pk %}" class="dropdown-item">Редактировать</a>
                                <a href="{% url 'accounts:delete_user' request.user.pk%}" class="dropdown-item">Удалить</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Выйти</a>
                            </div>
                        </li>
                    {% endif %}
                    {% block menu_links %}{% endblock %}
                </ul>
            </div>
        </nav>
    </div>
</header>
<div class="container mt-3">
    {% block content %}{% endblock %}
</div>
<script src={% static "/js/jquery-3.4.1.min.js"%}></script>
<script src={% static "/js/popper.min.js"%}></script>
<script src={% static "/js/bootstrap.min.js"%}></script>
{% block script %}{% endblock %}
</body>
</html>