source/accounts/urls.py
from django.urls import path

from accounts.views import UserListView, UserLogoutView, UserLoginView, UserCreateView, UserChangeView, UserDeleteView

urlpatterns = [
    path('users/register/', UserCreateView.as_view(), name='register_user'),
    path('users/<int:pk>/edit/', UserChangeView.as_view(), name='change_user'),
    path('users/login/', UserLoginView.as_view(), name='login'),
    path('users/logout/', UserLogoutView.as_view(), name='logout'),
    path('users/', UserListView.as_view(), name='list_users'),
    path('users/<int:pk>/delete/', UserDeleteView.as_view(), name='delete_user'),
]

app_name = 'accounts'

source/main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views.article_views import ArticleListView, ArticleEditView, ArticleDeleteView, ArticleCreateView
from webapp.views.category_views import CategoryListView, CategoryEditView

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='list_categories'),
    path('categories/<int:pk>/edit/', CategoryEditView.as_view(), name='edit_category'),
    path('', ArticleListView.as_view(), name='list_articles'),
    path('articles/add/', ArticleCreateView.as_view(), name='add_article'),
    path('articles/<int:pk>/edit/', ArticleEditView.as_view(), name='edit_article'),
    path('articles/<int:pk>/delete/', ArticleDeleteView.as_view(), name='delete_article'),
]

app_name = 'webapp'

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=30, verbose_name='Название категории')
    parent_id = models.ForeignKey('self', null=True, blank=True, verbose_name='Название основной категории',
                                  on_delete=models.PROTECT)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Categories'

class Article(models.Model):
    category_id = models.ForeignKey('webapp.Category', verbose_name='Категория', on_delete=models.PROTECT)
    user_id = models.ForeignKey(User, verbose_name='Автор статьи', null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=50, verbose_name='Название статьи')
    description = models.TextField(max_length=3000, verbose_name='Текст статьи')
    image = models.ImageField(upload_to='articles_images/', verbose_name='Аватар статьи')

    def __str__(self):
        if self.user_id:
            return "Статья {} от {}".format(self.title, self.user_id.username)
        else:
            return "Статья {}".format(self.title)

source/webapp/forms.py
from django import forms

from webapp.models import Category, Article


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title', 'parent_id']


class ArticleFormForAuthor(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'category_id', 'description', 'image']


class ArticleFormForStaff(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'category_id', 'user_id', 'description', 'image']

source/webapp/views/article_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, UpdateView, CreateView

from webapp.forms import ArticleFormForAuthor, ArticleFormForStaff
from webapp.models import Article


class ArticleListView(PermissionRequiredMixin, ListView):
    model = Article
    template_name = 'article/list.html'
    context_object_name = 'articles'
    paginate_by = 10
    paginate_orphans = 2
    permission_required = ['webapp.view_article']
    permission_denied_message = ['Доступ ограничен']


class ArticleEditView(UserPassesTestMixin, UpdateView):
    model=Article
    form_class = ArticleFormForAuthor
    template_name = 'article/edit.html'

    def form_valid(self, form):
        self.object = form.save()
        self.object.user_id = self.request.user
        return super(ArticleEditView, self).form_valid(form)

    def get_form(self, form_class=None):
        if self.request.user.has_perm('auth.view_user'):
            self.form_class = ArticleFormForStaff
        return super(ArticleEditView, self).get_form(form_class)

    def get_success_url(self):
        return reverse('webapp:list_articles')

    def get_article(self):
        article_pk = self.kwargs['pk']
        return get_object_or_404(Article, pk=article_pk)

    def test_func(self):
        article = self.get_article()
        return self.request.user.has_perm('webapp.change_article') or self.request.user.id == article.user_id.id


class ArticleDeleteView(PermissionRequiredMixin, View):
    permission_required = ['webapp.delete_article']
    permission_denied_message = ['Доступ ограничен']

    def get(self, request, *args, **kwargs):
        article = self.get_article()
        article.delete()
        return redirect('webapp:list_articles')

    def get_article(self):
        article_pk = self.kwargs['pk']
        return get_object_or_404(Article, pk=article_pk)


class ArticleCreateView(PermissionRequiredMixin, CreateView):
    model = Article
    form_class = ArticleFormForAuthor
    template_name = 'article/create.html'
    permission_required = ['webapp.add_article']
    permission_denied_message = ['Доступ ограничен']

    def get_success_url(self):
        return reverse('webapp:list_articles')

    def get_form(self, form_class=None):
        if self.request.user.has_perm('auth.view_user'):
            self.form_class = ArticleFormForStaff
        return super(ArticleCreateView, self).get_form(form_class)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            self.object = form.save()
            if not request.user.has_perm('webapp.view_user'):
                self.object.user_id = request.user
                self.object.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

source/webapp/views/category_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import ListView, UpdateView

from webapp.forms import CategoryForm
from webapp.models import Category


class CategoryListView(PermissionRequiredMixin, ListView):
    model = Category
    template_name = 'category/list.html'
    context_object_name = 'categories'
    paginate_by = 10
    paginate_orphans = 2
    permission_required = ['webapp.view_category']
    permission_denied_message = ['Доступ ограничен']
    ordering = ['title']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['form'] = CategoryForm
        return context


class CategoryEditView(PermissionRequiredMixin, UpdateView):
    model = Category
    fields = ['title', 'parent_id']
    template_name = 'category/category_edit.html'
    permission_required = ['webapp.change_category']
    permission_denied_message = ['Доступ ограничен']

    def get_success_url(self):
        return reverse('webapp:list_categories')

source/webapp/templates/article/create.html
{% extends 'base.html' %}
{% block title %}
   Добавить статью
{% endblock %}
{% block menu_links %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'webapp:list_articles' %}">К списку статей</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'webapp:list_categories' %}">К списку категорий</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:list_users' %}">К списку пользователей</a>
    </li>
{% endblock %}
{% block content %}
    <h1>Добавить статью</h1>
    <form action="{% url 'webapp:add_article' %}" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text='Добавить' button_id='addArticle'%}
    </form>
{% endblock %}

source/webapp/templates/article/edit.html
{% extends 'base.html' %}
{% block title %}
   Редактировать статью
{% endblock %}
{% block menu_links %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'webapp:list_articles' %}">К списку статей</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'webapp:list_categories' %}">К списку категорий</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:list_users' %}">К списку пользователей</a>
    </li>
{% endblock %}
{% block content %}
    <h1>Редактировать статью</h1>
    <form action="{% url 'webapp:edit_category' article.pk %}" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text='Редактировать' button_id='editArticle'%}
    </form>
{% endblock %}

source/webapp/templates/article/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Статьи
{% endblock %}

{% block menu_links %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'webapp:add_article' %}">Добавить статью</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'webapp:list_categories' %}">К списку категорий</a>
    </li>
    {% if perms.auth.view_user %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="usersDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Пользователи
                </a>
                <div class="dropdown-menu" aria-labelledby="usersDropdown">
                    <a class="dropdown-item" href="{% url 'accounts:list_users' %}">К списку пользователей</a>
                    <a class="dropdown-item" href="{% url 'accounts:register_user' %}">Добавить пользователя</a>
                </div>
            </li>
    {% endif %}
{% endblock %}
{% block content %}
    {% include  'partial/pagination.html' %}
    <div class="list-group" id="articleList">
        {% for article in articles %}
            <div class="card">
                <div class="card-header position-relative" id="heading{{ article.pk }}">
                    <a class="list-group-item  collapsed" data-toggle="collapse" data-target="#collapse{{ article.pk }}" aria-expanded="true" aria-controls="collapse{{ article.pk }}">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ article.title }}</h5>
                            <small>Категория: {{ article.category_id.title }}</small>
                        </div>
                        <p class="mb-1">{{ article.description|truncatewords:10 }}</p>
                        <small>Автор: {{ article.user_id.username }}</small>
                    </a>
                    {% if request.user.id == article.user_id.id or perms.webapp.change_article %}
                        <div class="btn-group position-absolute article-links">
                            <a class="btn btn-success" href="{% url 'webapp:edit_article' article.pk%}"><i class="fas fa-edit"></i></a>
                            {% if perms.webapp.delete_article%}
                                <button type="button" class="btn btn-danger delete-button" data-toggle="modal" data-target="#deleteModal" data-article-id="{{ article.pk }}">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
                <div id="collapse{{ article.pk }}" class="collapse" aria-labelledby="heading{{ article.pk }}" data-parent="#articleList">
                    <div class="card-body">
                        {{ article.description|escape|linebreaks }}
                    </div>
                    <div class="d-flex justify-content-center pb-5">
                        <img src="{{ article.image.url }}" class="card-img-top article-avatar" alt="{{ article.image.name }}">
                    </div>

                </div>
            </div>

        {% endfor %}
    </div>
    {% include  'partial/pagination.html' %}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Удалить статью?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <a href="#" class="btn btn-danger" id="deleteArticle">Удалить</a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block script %}
    <script src="{% static 'js/article_script.js'%}"></script>
{% endblock %}